version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-faucet}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-faucetpass}
      POSTGRES_DB: ${POSTGRES_DB:-faucetdb}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-faucet}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - "./logs:/app/logs"
      - "./config:/app/config"
volumes:
  pg_data:
